const productColors = [
  { name: "Red", hex: "#FF0000" },
  { name: "Green", hex: "#00FF00" },
  { name: "Blue", hex: "#0000FF" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Cyan", hex: "#00FFFF" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Purple", hex: "#800080" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Gray", hex: "#808080" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "Lime", hex: "#00FF00" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "Violet", hex: "#EE82EE" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Maroon", hex: "#800000" },
  { name: "Olive", hex: "#808000" },
  { name: "Teal", hex: "#008080" },
  { name: "Navy", hex: "#000080" },
  { name: "Lavender", hex: "#E6E6FA" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Peach", hex: "#FFDAB9" },
  { name: "Mint", hex: "#98FF98" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Salmon", hex: "#FA8072" },
  { name: "Khaki", hex: "#F0E68C" },
  { name: "Plum", hex: "#DDA0DD" },
  { name: "Crimson", hex: "#DC143C" },
  { name: "Periwinkle", hex: "#CCCCFF" },
  { name: "Azure", hex: "#007FFF" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Chartreuse", hex: "#7FFF00" },
  { name: "Aquamarine", hex: "#7FFFD4" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Tomato", hex: "#FF6347" },
  { name: "Wheat", hex: "#F5DEB3" },
  { name: "Steel Blue", hex: "#4682B4" },
  { name: "Dodger Blue", hex: "#1E90FF" },
  { name: "Lemon Chiffon", hex: "#FFFACD" },
  { name: "Seashell", hex: "#FFF5EE" },
  { name: "Sienna", hex: "#A0522D" },
  { name: "Orchid", hex: "#DA70D6" },
  { name: "Hot Pink", hex: "#FF69B4" },
  { name: "Slate Gray", hex: "#708090" },
  { name: "Forest Green", hex: "#228B22" },
  { name: "Midnight Blue", hex: "#191970" },
  { name: "Rosy Brown", hex: "#BC8F8F" },
];

export default productColors;